config/routes.rb
Rails.application.routes.draw do

  namespace :auth do
    resources :users, only: [:create]
    resource :session, only: [:create]
    resource :confirmation, only: [:new]
  end

  namespace :admin do
    resources :posts do
      get 'statuses/:status', to: 'posts#index', as: :by_status, on: :collection
    end
    root to: "posts#index"
  end

  post 'login' => 'auth/sessions#create'
  get 'login' => 'auth/sessions#new'
  delete 'logout' => 'auth/sessions#destroy'

  get 'register' => 'auth/users#new'
  resources :posts do
    resources :comments
  end

  root to: 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates_presence_of :user
end

app/models/post.rb
class Post < ApplicationRecord
  enum status: { draft: 0, published: 1 } do
    event :publish do
      after do
        self.published_at = DateTime.now
        self.save
      end

      transition :draft => :published
    end

    event :unpublish do
      transition :published => :draft
    end
  end

  attr_accessor :state_event
  after_save :trigger_state, if: :state_event

  private def trigger_state
    send(state_event) if send(:"can_#{state_event}?")
  end

  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings
  has_many :posts, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :role, inclusion: %w(admin user)
  before_create :generate_confirmation_token

  def generate_confirmation_token
    self.confirmation_token = SecureRandom.hex
  end

  def confirmed?
    self.confirmed_at.present?
  end

  def admin?
    self.role == 'admin'
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :ensure_admin_user!

  def ensure_admin_user!
    unless current_user and current_user.admin?
      redirect_to root_path, danger: "You don't belong there"
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
  def index
    @posts = scoped_posts.order("created_at DESC").page(params[:page]).per(10)
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.where(id: params[:id]).first
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to admin_posts_path
    else
      # render the form again
    end
  end

  def update
    @post = Post.where(id: params[:id]).first
    if @post.update_attributes(post_params)
      redirect_to admin_posts_path
    else
      # render the edit form again
    end
  end

  def destroy
    @post = Post.where(id: params[:id]).first
    if @post.destroy
      redirect_to posts_path
    else
      #
    end
  end

  private

  def scoped_posts
    if params[:status].present?
      Post.send(params[:status])
    else
      Post.all
    end
  end

  def post_params
    params.require(:post).permit(:state_event, :title, :body, :tag_ids => [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :danger, :info, :warning, :success
  def current_user
    @current_user ||= User.where(id: session[:user_id]).first
  end

  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.where(id: params[:post_id]).first
    @comment = @post.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to post_path(@post)
    else
      #error handling
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
  def new

  end

  def create
    @user = User.where(confirmation_token: params[:token]).first
    @user.confirmed_at = DateTime.now
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      ##
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.published.order("published_at DESC").all
  end

  def show
    @post = Post.where(id: params[:id]).first
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.where(email: params[:email]).first
    if @user and @user.confirmed? and @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, success: "You have signed in!"
    else
      flash[:error] = "Invalid email or password"
      redirect_to login_path, danger: "invalid email or password"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  def new
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.register_email(@user).deliver_now
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/admin/posts_helper.rb
module Admin
  module PostsHelper
    class << self
      def render_states(view)
        view.sanitize(
          statuses(view).map do |status, path|
            view.content_tag :li, class: active(view, path) do
              view.link_to status, path
            end
          end.join
        )
      end

      private

      def active(view, path)
        view.current_page?(path) ? 'active' : nil
      end

      def statuses(view)
        # { 'all' => admin_posts_path,
        #   'draft' => by_status_admin_posts_path('draft'),
        #   'published' => by_status_admin_posts_path('published') }

        { 'all' => view.admin_posts_path }.merge(
          Post.statuses.keys.inject({}) do |hash, status|
            hash.merge(status => view.by_status_admin_posts_path(status))
          end
        )
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_user_auth_nav
    if current_user
      render 'signed_in'
    else
      render 'signed_out'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/posts/_form.html.erb
<%= form_for [:admin, @post] do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name do |t| %>
      <div class="checkbox">
        <%= t.label do %>
          <%= t.check_box + t.text %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-block btn-success" %>
  </div>
<% end %>

app/views/admin/posts/_post.html.erb
<%= div_for post, class: "col-md-8 col-md-offset-2" do %>
  <div class='row'>
    <div class='col-md-8'>
  <p><%= post.body %> </p>
  <p> Comments(<%= post.comments.count %>) </p>
  <ul> <% post.tags.each do |tag| %>
    <li>
      <%= tag.name %>
    </li>
      <% end %>
  </ul>
</div>
  <div class='col-md-3'>
    <%= link_to 'Edit', edit_admin_post_path(post), class: 'btn btn-primary' %>
    <%= link_to 'Delete', edit_admin_post_path(post), method: :delete, class: 'btn btn-danger' %>
    <%= post.status %>
  </div>
</div>

<% end %>

app/views/admin/posts/actions/_draft.html.erb
<%= form_for [:admin, @post] do |f| %>
  <%= f.hidden_field :state_event, value: :publish %>
  <%= f.submit "Published", class: 'btn btn-success btn-block' %>
<% end %>

app/views/admin/posts/actions/_published.html.erb
<%= form_for [:admin, @post] do |f| %>
  <%= f.hidden_field :state_event, value: :unpublish %>
  <%= f.submit "Unpublish", class: 'btn btn-success btn-block' %>
<% end %>

app/views/admin/posts/edit.html.erb
<%= content_for :action_bar do %>
  <div class='action_bar container-fluid'>
    <div class="row">
      <div class='col-md-offset-10 col-md-2'>
        <%= render "admin/posts/actions/#{@post.status}" %>
      </div>
    </div>
  </div>
<% end %>

<div class="col-md-8 col-md-offset-2">
  <%= render 'form' %>
</div>

app/views/admin/posts/index.html.erb
<%= content_for :action_bar do %>
  <div class='action_bar container-fluid'>
    <div class='row'>
      <div class='col-md-10'>
        <ul class='nav nav-pills'>
          <%= Admin::PostsHelper.render_states(self) %>
        </ul>
      </div>
      <div class='col-md-2'>
        <%= link_to "New Post", new_admin_post_path, class: 'btn btn-success btn-block' %>
      </div>
    </div>
  </div>
<% end %>


<% @posts.each do |post| %>
  <%= render post %>
<% end %>

<%= paginate @posts %>

app/views/admin/posts/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <%= render 'form' %>
</div>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <div class='container'>
    <a class="navbar-brand" href="#">
      <%= link_to 'Writefully', root_path, class: 'navbar-brand' %>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto navbar-right">
        <%= render_user_auth_nav %> <span class="sr-only">(current)</span>
      </ul>
    </div>
  </div>
</nav>

app/views/application/_signed_in.html.erb
<li class="nav-item">
  <%= link_to current_user.email, class: 'nav-link' %>
</li>
<li class="nav-item">
  <%= link_to 'Sign Out', logout_path, method: :delete, class: 'nav-link' %>
</li>

app/views/application/_signed_out.html.erb
<li class="nav-item">
  <%= link_to 'Sign in', login_path, class: 'nav-link' %>
</li>
<li class="nav-item">
  <%= link_to 'Sign up', register_path, class: 'nav-link' %>
</li>

app/views/comments/_comments.html.erb
<hr>
<h2>Comments</h2>
<% @post.comments.each do |comment| %>
  <div class='panel panel-default'>
    <div class='panel-body'>
      <%= comment.body %>
    </div>
    <div class='author'>
      Commented by: <%= comment.user.email %>
    </div>
  </div>
<% end %>

<%= form_for [@post, @post.comments.build] do |f| %>
  <div class='form-group'>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class='actions'>
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name do |t| %>
      <div class="checkbox">
        <%= t.label do %>
          <%= t.check_box + t.text %>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: "btn btn-block btn-success" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<%= div_for post, class: "col-md-8 col-md-offset-2" do %>
  <h2><%= link_to post.title, post_path(post) %> </h2>
  <p><%= post.body %> </p>
  <p> Comments(<%= post.comments.count %>) </p>
  <ul> <% post.tags.each do |tag| %>
    <li>
      <%= tag.name %>
    </li>
      <% end %>
  </ul>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= render post %>
<% end %>

app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>
<p> <%= @post.body %> </p>

<hr>
<h2> Comments </h2>
<% @post.comments.each do |comment| %>
  <div class="panel panel-default">
    <div class="panel-body">
      <%= comment.body %>
    </div>
    <div class='author'>
      Commented by: <%= comment.user.email %>
    </div>
  </div>
<% end %>

<%= form_for [@post, @post.comments.build] do |f| %>
  <div class="form-group">
    <%= f.text_area :body, class: 'form-control' %>
  </div>

  <div class='actions'>
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>